services:
  ntfy:
    ports:
      - "127.0.0.1:8080:80"
    environment:
      TZ: America/New_York

  weather-app:
    command: python main.py
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      FLASK_DEBUG: "1"