services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command: serve
    volumes:
      - ./ntfy/cache:/var/cache/ntfy
      - ./ntfy/etc:/etc/ntfy

  weather-app:
    build: .
    container_name: weather-app
    env_file: .env
    environment:
      DB_PATH: /data/weather.db
    volumes:
      - ./data:/data
    depends_on:
      - ntfy